# Generated by Django 4.1.3 on 2023-02-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xceef598477f669bc4c56894ffbb2b343', max_length=128),
        ),
    ]
