# Generated by Django 4.1.3 on 2023-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x4fdae58931d4420c67c44efc17909ab7', max_length=128),
        ),
    ]
