# Generated by Django 4.1.3 on 2023-02-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0xa5fca5d9e2b152cfaf0556e04fe82fd3', max_length=128),
        ),
    ]
