# Generated by Django 4.1.3 on 2023-02-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x1bfeecb5962fae546587bc99c2db376e', max_length=128),
        ),
    ]
