# Generated by Django 4.1.3 on 2023-02-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x132f3305c977cd49f4da6ed2dcc2cf69', max_length=128),
        ),
    ]
