# Generated by Django 4.1.3 on 2023-02-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(default='0x832ffae3dac8eaf457aa7ef1012b99fd', max_length=128),
        ),
    ]
