# Generated by Django 4.1.3 on 2023-02-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyadmin', '0003_agent_customer_property_slot_viewing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address_line_two',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
