# Generated by Django 4.1.3 on 2023-02-08 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyadmin', '0004_alter_property_address_line_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='date_of_viewing',
            field=models.DateField(default=datetime.date(2020, 8, 28)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
