# Generated by Django 4.1.3 on 2023-02-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyadmin', '0006_viewing_property_alter_viewing_date_of_viewing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewing',
            unique_together={('date_of_viewing', 'slot', 'property')},
        ),
    ]
