# Generated by Django 4.1.3 on 2023-02-13 06:27

from django.db import migrations, models
import propertyadmin.models
import propertyadmin.validators


class Migration(migrations.Migration):

    dependencies = [
        ('propertyadmin', '0007_alter_viewing_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=propertyadmin.models.image_path_handler, validators=[propertyadmin.validators.FileValidator(content_types=('image/jpeg', 'image/png', 'image/gif', 'image/tiff', 'application/x-empty'), max_size=5120000)])),
            ],
        ),
    ]
