# Generated by Django 4.1.3 on 2023-02-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyadmin', '0008_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='headline',
            field=models.CharField(default='the', max_length=50),
            preserve_default=False,
        ),
    ]
