# Generated by Django 4.1.3 on 2023-02-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyadmin', '0009_newsitem_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='article',
            field=models.CharField(max_length=500),
        ),
    ]
